Skip tests id scsi_debug is compiled-in or in use.
We need standalone scsi_debug module for some tests.

diff --git a/tests/align-test b/tests/align-test
--- a/tests/align-test
+++ b/tests/align-test
@@ -181,6 +181,10 @@ fi
 dm_crypt_features
 modprobe --dry-run scsi_debug || exit 77
 cleanup
+if [ -d /sys/module/scsi_debug ] ; then
+	echo "Cannot use scsi_debug module (in use or compiled-in), test skipped."
+	exit 77
+fi
 
 echo "# Create desktop-class 4K drive"
 echo "# (logical_block_size=512, physical_block_size=4096, alignment_offset=0)"
diff --git a/tests/align-test2 b/tests/align-test2
--- a/tests/align-test2
+++ b/tests/align-test2
@@ -163,6 +163,10 @@ fi
 dm_crypt_features
 modprobe --dry-run scsi_debug || exit 77
 cleanup
+if [ -d /sys/module/scsi_debug ] ; then
+	echo "Cannot use scsi_debug module (in use or compiled-in), test skipped."
+	exit 77
+fi
 
 add_device dev_size_mb=32
 echo $PWD1 | $CRYPTSETUP luksFormat $FAST_PBKDF --type luks2 $DEV -q  >/dev/null || fail
diff --git a/tests/compat-test b/tests/compat-test
--- a/tests/compat-test
+++ b/tests/compat-test
@@ -177,6 +177,10 @@ scsi_debug_teardown() {
 
 function add_scsi_device() {
 	scsi_debug_teardown $DEV
+	if [ -d /sys/module/scsi_debug ] ; then
+		echo "Cannot use scsi_debug module (in use or compiled-in), test skipped."
+		exit 77
+	fi
 	modprobe scsi_debug $@ delay=0
 	if [ $? -ne 0 ] ; then
 		echo "This kernel seems to not support proper scsi_debug module, test skipped."
diff --git a/tests/keyring-compat-test b/tests/keyring-compat-test
--- a/tests/keyring-compat-test
+++ b/tests/keyring-compat-test
@@ -96,6 +96,12 @@ function fips_mode()
 }
 
 add_device() {
+	rmmod scsi_debug 2>/dev/null
+	if [ -d /sys/module/scsi_debug ] ; then
+		echo "Cannot use scsi_debug module (in use or compiled-in), test skipped."
+		exit 77
+	fi
+
 	modprobe scsi_debug $@ delay=0
 	if [ $? -ne 0 ] ; then
 		echo "This kernel seems to not support proper scsi_debug module, test skipped."
diff --git a/tests/reencryption-compat-test2 b/tests/reencryption-compat-test2
--- a/tests/reencryption-compat-test2
+++ b/tests/reencryption-compat-test2
@@ -74,6 +74,10 @@ function skip()
 
 function add_scsi_device() {
 	del_scsi_device
+	if [ -d /sys/module/scsi_debug ] ; then
+		echo "Cannot use scsi_debug module (in use or compiled-in), test skipped."
+		exit 77
+	fi
 	modprobe scsi_debug $@ delay=0
 	if [ $? -ne 0 ] ; then
 		echo "This kernel seems to not support proper scsi_debug module, test skipped."
