Unify use of tabulators in tests.

diff --git a/tests/blockwise-compat b/tests/blockwise-compat
--- a/tests/blockwise-compat
+++ b/tests/blockwise-compat
@@ -80,24 +80,24 @@ falloc() {
 
 run_all_in_fs() {
 	for file in $(ls img_fs_*.img.xz) ; do
-	    echo "Run tests in $file put on top block device."
-	    xz -d -c $file | dd of=$DEV bs=1M 2>/dev/null || fail "bad image"
-	    [ ! -d $MNT_DIR ] && mkdir $MNT_DIR
-	    mount $DEV $MNT_DIR
-	    if [ $? -ne 0 ]; then
-	        echo "Mounting image $file failed, skipped."
-	        continue;
-	    fi
-	    rm -rf $MNT_DIR/* 2>/dev/null
-	    local tfile=$MNT_DIR/bwunit_tstfile
-	    falloc $DEVSIZEMB $tfile || fail "enospc?"
-	    local iobsize=$(stat -c "%o" $tfile)
-	    test -n "$iobsize" -a $iobsize -gt 0 || fail
-	    local oldbsize=$BSIZE
-	    BSIZE=$iobsize
-	    run_all $tfile
-	    BSIZE=$oldbsize
-	    umount $MNT_DIR
+		echo "Run tests in $file put on top block device."
+		xz -d -c $file | dd of=$DEV bs=1M 2>/dev/null || fail "bad image"
+		[ ! -d $MNT_DIR ] && mkdir $MNT_DIR
+		mount $DEV $MNT_DIR
+		if [ $? -ne 0 ]; then
+			echo "Mounting image $file failed, skipped."
+			continue;
+		fi
+		rm -rf $MNT_DIR/* 2>/dev/null
+		local tfile=$MNT_DIR/bwunit_tstfile
+		falloc $DEVSIZEMB $tfile || fail "enospc?"
+		local iobsize=$(stat -c "%o" $tfile)
+		test -n "$iobsize" -a $iobsize -gt 0 || fail
+		local oldbsize=$BSIZE
+		BSIZE=$iobsize
+		run_all $tfile
+		BSIZE=$oldbsize
+		umount $MNT_DIR
 	done
 }
 
