Support large IV count option for plain device
The iv_large_sector option is supported in dm-crypt since introduction
of larger sectors encryption.
It counts Initialization Vector (IV) in larger sector size (if set) instead
of 512 bytes sectors.

This option does not have any performance or security impact, but it can be
used for accessing incompatible existing disk images from other systems.
(It is used internally in BitLocker compatibily code).

This patch allows it to be used for plain type device, so users
can manually map foreign disk images.
Only open action with plain device and sector size > 512 bytes is supported.

diff --git a/tests/device-test b/tests/device-test
--- a/tests/device-test
+++ b/tests/device-test
@@ -239,6 +239,15 @@ else
 		check_sector_size $S
 		$CRYPTSETUP close $DEV_NAME || fail
 	done
+
+	echo -e "$PWD1" | $CRYPTSETUP open --type plain --hash sha256 $DEV $DEV_NAME --iv-large-sectors >/dev/null 2>&1 && fail
+	for S in 1024 2048 4096; do
+		echo -n "[$S/IV]"
+		echo -e "$PWD1" | $CRYPTSETUP open -q --type plain --hash sha256 $DEV $DEV_NAME --sector-size $S --iv-large-sectors || fail
+		check_sector_size $S
+		dmsetup table $DEV_NAME | grep -q "iv_large_sectors" || fail
+		$CRYPTSETUP close $DEV_NAME || fail
+	done
 	echo
 
 	echo -n "LUKS2 sector size:"
