Silence all modprobe/rmmod calls in tests.
On systems where are modules compiled-in or missing this produces nois,
test will be skipped later anyway.

diff --git a/tests/device-test b/tests/device-test
--- a/tests/device-test
+++ b/tests/device-test
@@ -17,7 +17,7 @@ cleanup() {
 	    umount -f $MNT_DIR 2>/dev/null
 	    rmdir $MNT_DIR 2>/dev/null
 	fi
-	rmmod scsi_debug 2>/dev/null
+	rmmod scsi_debug >/dev/null 2>&1
 }
 
 fail()
@@ -37,7 +37,7 @@ skip()
 }
 
 add_device() {
-	rmmod scsi_debug 2>/dev/null
+	rmmod scsi_debug >/dev/null 2>&1
 	[ -d /sys/module/scsi_debug ] && skip "Cannot use scsi_debug module (in use or compiled-in)."
 
 	modprobe scsi_debug $@ delay=0
@@ -51,7 +51,7 @@ add_device() {
 
 function dm_crypt_features()
 {
-	modprobe dm-crypt || fail "dm-crypt failed to load"
+	modprobe dm-crypt >/dev/null 2>&1 || fail "dm-crypt failed to load"
 	VER_STR=$(dmsetup targets | grep crypt | cut -f2 -dv)
 	[ -z "$VER_STR" ] && fail "Failed to parse dm-crypt version."
 
@@ -322,7 +322,7 @@ for F in LUKS1 LUKS2 BITLK TCRYPT; do
 	udevadm settle >/dev/null 2>&1
 	$CRYPTSETUP status $DEV_NAME >/dev/null 2>&1 || fail
 	dmsetup remove $DEV_NAME --retry || fail
-	rmmod scsi_debug
+	rmmod scsi_debug >/dev/null 2>&1
 	echo -n "[OK] "
 done
 echo
diff --git a/tests/keyring-compat-test b/tests/keyring-compat-test
--- a/tests/keyring-compat-test
+++ b/tests/keyring-compat-test
@@ -35,7 +35,7 @@ function remove_mapping()
 	# unlink whole test keyring
 	[ -n "$TEST_KEYRING" ] && keyctl unlink $TEST_KEYRING "@u" >/dev/null
 
-	rmmod scsi_debug 2>/dev/null
+	rmmod scsi_debug >/dev/null 2>&1
 
 	rm -f $CHKS_DMCRYPT $CHKS_KEYRING
 }
@@ -96,7 +96,7 @@ function fips_mode()
 }
 
 add_device() {
-	rmmod scsi_debug 2>/dev/null
+	rmmod scsi_debug >/dev/null 2>&1
 	if [ -d /sys/module/scsi_debug ] ; then
 		echo "Cannot use scsi_debug module (in use or compiled-in), test skipped."
 		exit 77
@@ -120,7 +120,7 @@ which dmsetup >/dev/null 2>&1 || skip "Cannot find dmsetup, test skipped"
 which keyctl >/dev/null 2>&1 || skip "Cannot find keyctl, test skipped"
 which xxd >/dev/null 2>&1 || skip "Cannot find xxd, test skipped"
 which sha1sum > /dev/null 2>&1 || skip "Cannot find sha1sum, test skipped"
-modprobe dm-crypt || fail "dm-crypt failed to load"
+modprobe dm-crypt >/dev/null 2>&1 || fail "dm-crypt failed to load"
 dm_crypt_keyring_support || skip "dm-crypt doesn't support kernel keyring, test skipped."
 
 test_and_prepare_keyring
diff --git a/tests/luks2-reencryption-test b/tests/luks2-reencryption-test
--- a/tests/luks2-reencryption-test
+++ b/tests/luks2-reencryption-test
@@ -62,14 +62,14 @@ scsi_debug_teardown() {
 	local _tries=15;
 
 	while [ -b "$1" -a $_tries -gt 0 ]; do
-		rmmod scsi_debug 2> /dev/null
+		rmmod scsi_debug >/dev/null 2>&1
 		if [ -b "$1" ]; then
 			sleep .1
 			_tries=$((_tries-1))
 		fi
 	done
 
-	test ! -b "$1" || rmmod scsi_debug 2> /dev/null
+	test ! -b "$1" || rmmod scsi_debug >/dev/null 2>&1
 }
 
 function remove_mapping()
@@ -99,7 +99,7 @@ function remove_mapping()
 	[ -n "$LOOPDEV" ] && losetup -d $LOOPDEV
 	unset LOOPDEV
 	rm -f $IMG $IMG_HDR $KEY1 $VKEY1 $DEVBIG $DEV_LINK >/dev/null 2>&1
-	rmmod scsi_debug 2> /dev/null
+	rmmod scsi_debug >/dev/null 2>&1
 	scsi_debug_teardown $DEV
 }
 
@@ -688,7 +688,7 @@ function valgrind_run()
 [ ! -x "$CRYPTSETUP" ] && skip "Cannot find $CRYPTSETUP, test skipped."
 fips_mode && skip "This test cannot be run in FIPS mode."
 modprobe --dry-run scsi_debug || exit 77
-modprobe dm-crypt || fail "dm-crypt failed to load"
+modprobe dm-crypt >/dev/null 2>&1 || fail "dm-crypt failed to load"
 modprobe dm-delay > /dev/null 2>&1
 dm_crypt_features
 
