fvault2: test volume key dump

diff --git a/tests/fvault2-compat-test b/tests/fvault2-compat-test
--- a/tests/fvault2-compat-test
+++ b/tests/fvault2-compat-test
@@ -44,10 +44,12 @@ function skip()
 
 function produce_dump()
 {
-	local image=$1
-	local passphrase=$2
-	echo -n "$passphrase" | "$CRYPTSETUP" fvault2Dump "$image" \
-		--key-file -
+	"$CRYPTSETUP" fvault2Dump "$1" || fail
+}
+
+function produce_dump_key()
+{
+	echo "$2" | "$CRYPTSETUP" fvault2Dump "$1" --dump-volume-key || fail
 }
 
 function check_dump()
@@ -100,14 +102,18 @@ fi
 
 echo "HEADER CHECK"
 IMG="$TST_DIR/small"
+PWD="heslo123"
+
 echo -n " $IMG"
-dump=$(produce_dump $IMG heslo123)
+dump=$(produce_dump $IMG)
 check_dump "$dump" 'Physical volume UUID' fc52bfae-5a1f-4f9b-b3a6-f33303a0e401
 check_dump "$dump" 'Family UUID' 33a76caa-1481-4bc5-8d04-1ac1707c19c0
 check_dump "$dump" 'Logical volume offset' '67108864 [bytes]'
 check_dump "$dump" 'Logical volume size' '167772160 [bytes]'
 check_dump "$dump" 'PBKDF2 iterations' 204222
 check_dump "$dump" 'PBKDF2 salt' '2c 24 9e db 66 63 d6 fb cc 79 05 b7 a4 d7 27 52'
+dump=$(produce_dump_key $IMG heslo123)
+check_dump "$dump" 'Volume key' '20 73 4d 33 89 21 27 74 d7 61 0c 29 d7 32 88 09 16 f3 be 14 c4 b1 2a c7 aa f0 7e 5c cc 77 b3 19'
 echo " [OK]"
 
 if [ $(id -u) != 0 ]; then
