integrity: support detached data device.
Since the kernel 4.18 there is a possibility to speficy external
data device for dm-integrity that stores all integrity tags.

The new option --data-device in integritysetup uses this feature.

diff --git a/tests/integrity-compat-test b/tests/integrity-compat-test
--- a/tests/integrity-compat-test
+++ b/tests/integrity-compat-test
@@ -8,6 +8,7 @@ INTSETUP_LIB_VALGRIND=../.libs
 
 DEV_NAME=dmc_test
 DEV=test123.img
+DEV2=test124.img
 KEY_FILE=key.img
 
 dmremove() { # device
@@ -17,13 +18,13 @@ dmremove() { # device
 
 cleanup() {
 	[ -b /dev/mapper/$DEV_NAME ] && dmremove $DEV_NAME
-	rm -f $DEV $KEY_FILE >/dev/null 2>&1
+	rm -f $DEV $DEV2 $KEY_FILE >/dev/null 2>&1
 }
 
 fail()
 {
 	echo
-	[ -n "$1" ] && echo "FAILED at line $(caller)"
+	echo "FAILED at line $(caller)"
 	cleanup
 	exit 100
 }
@@ -34,10 +35,27 @@ skip()
 	exit 77
 }
 
+function dm_integrity_features()
+{
+	VER_STR=$(dmsetup targets | grep integrity | cut -f2 -dv)
+	[ -z "$VER_STR" ] && skip "Cannot find dm-integrity target, test skipped."
+
+	VER_MAJ=$(echo $VER_STR | cut -f 1 -d.)
+	VER_MIN=$(echo $VER_STR | cut -f 2 -d.)
+	VER_PTC=$(echo $VER_STR | cut -f 3 -d.)
+
+	[ $VER_MAJ -lt 1 ] && return
+	[ $VER_MIN -gt 1 ] && {
+		DM_INTEGRITY_META=1
+		DM_INTEGRITY_RECALC=1
+	}
+}
+
 add_device() {
 	cleanup
 	dd if=/dev/urandom of=$KEY_FILE bs=1 count=512 >/dev/null 2>&1
 	dd if=/dev/zero of=$DEV bs=1M count=32 >/dev/null 2>&1
+	dd if=/dev/zero of=$DEV2 bs=1M count=32 >/dev/null 2>&1
 	sync
 }
 
@@ -83,6 +101,18 @@ function valgrind_run()
     INFOSTRING="$(basename ${BASH_SOURCE[1]})-line-${BASH_LINENO[0]}" ./valg.sh ${INTSETUP_VALGRIND} "$@"
 }
 
+int_check_sum_only() # checksum
+{
+	VSUM=$(sha256sum /dev/mapper/$DEV_NAME | cut -d' ' -f 1)
+	if [ "$VSUM" = "$1" ] ; then
+		echo -n "[CHECKSUM OK]"
+	else
+		echo "[FAIL]"
+		echo " Expecting $1 got $VSUM."
+		fail
+	fi
+}
+
 int_check_sum() # alg checksum [keyfile keysize]
 {
 	if [ -n "$4" ] ; then
@@ -97,14 +127,7 @@ int_check_sum() # alg checksum [keyfile keysize]
 
 	$INTSETUP open $DEV $DEV_NAME --integrity $1 $KEY_PARAMS || fail "Cannot activate device."
 
-	VSUM=$(sha256sum /dev/mapper/$DEV_NAME | cut -d' ' -f 1)
-	if [ "$VSUM" = "$2" ] ; then
-		echo -n "[CHECKSUM OK]"
-	else
-		echo "[FAIL]"
-		echo " Expecting $2 got $VSUM."
-		fail
-	fi
+	int_check_sum_only $2
 }
 
 intformat() # alg alg_out tagsize sector_size csum [keyfile keysize]
@@ -263,7 +286,7 @@ int_mode() # alg tag_size sector_size [keyfile keysize]
 [ -n "$VALG" ] && valgrind_setup && INTSETUP=valgrind_run
 which hexdump >/dev/null 2>&1 || skip "WARNING: hexdump tool required."
 modprobe dm-integrity >/dev/null 2>&1
-dmsetup targets | grep integrity >/dev/null 2>&1 || skip "Cannot find dm-integrity target, test skipped."
+dm_integrity_features
 
 add_device
 intformat crc32c      crc32c          4  512 08f63eb27fb9ce2ce903b0a56429c68ce5e209253ba42154841ef045a53839d7
@@ -312,11 +335,26 @@ int_mode hmac-sha256 32 512  $KEY_FILE 32
 int_mode hmac-sha256 32 4096 $KEY_FILE 32
 
 echo -n "Recalculate tags in-kernel:"
-$INTSETUP format -q $DEV --no-wipe || fail "Cannot format device."
-$INTSETUP open $DEV $DEV_NAME --integrity-recalculate || fail "Cannot activate device with journal."
-$INTSETUP dump $DEV | grep -q recalculating
-if [ $? -eq 0 ] ; then
-	dd if=/dev/mapper/$DEV_NAME of=/dev/null bs=1M 2>/dev/null || fail "Cannot tags recalculate in-kernel"
+add_device
+if [ -n "$DM_INTEGRITY_RECALC" ] ; then
+	$INTSETUP format -q $DEV --no-wipe || fail "Cannot format device."
+	$INTSETUP open $DEV $DEV_NAME --integrity-recalculate || fail "Cannot activate device."
+	dd if=/dev/mapper/$DEV_NAME of=/dev/null bs=1M 2>/dev/null || fail "Cannot recalculate tags in-kernel"
+	int_check_sum_only 08f63eb27fb9ce2ce903b0a56429c68ce5e209253ba42154841ef045a53839d7
+	$INTSETUP close $DEV_NAME fail "Cannot deactivate device."
+	echo "[OK]"
+else
+	echo "[N/A]"
+fi
+
+echo -n "Recalculate tags in-kernel + separate device:"
+if [ -n "$DM_INTEGRITY_META" ] ; then
+	add_device
+	$INTSETUP format -q $DEV --data-device $DEV2 || fail "Cannot format device."
+	$INTSETUP open $DEV --data-device $DEV2 $DEV_NAME || fail "Cannot activate device."
+	int_check_sum_only 83ee47245398adee79bd9c0a8bc57b821e92aba10f5f9ade8a5d1fae4d8c4302
+	$INTSETUP status $DEV_NAME | grep -q 'metadata device:' || fail
+	$INTSETUP close $DEV_NAME fail "Cannot deactivate device."
 	echo "[OK]"
 else
 	echo "[N/A]"
