Allow reencryption metadata repair from cryptsetup.

diff --git a/tests/luks2-reencryption-mangle-test b/tests/luks2-reencryption-mangle-test
--- a/tests/luks2-reencryption-mangle-test
+++ b/tests/luks2-reencryption-mangle-test
@@ -172,6 +172,42 @@ EOF
 [ $? -eq 0 ] || fail "Expect script failed."
 }
 
+function img_run_reenc_fail()
+{
+local EXPECT_TIMEOUT=5
+[ -n "$VALG" ] && EXPECT_TIMEOUT=60
+# For now, we cannot run reencryption in batch mode for non-block device. Just fake the terminal here.
+expect_run - >/dev/null <<EOF
+proc abort {} { send_error "Timeout. "; exit 42 }
+set timeout $EXPECT_TIMEOUT
+eval spawn $CRYPTSETUP_RAW reencrypt $IMG $CS_PWPARAMS --disable-locks
+expect timeout abort "Are you sure? (Type 'yes' in capital letters):"
+send "YES\n"
+expect timeout abort eof
+catch wait result
+exit [lindex \$result 3]
+EOF
+local ret=$?
+[ $ret -eq 0 ] &&  fail "Reencryption passed (should have failed)."
+[ $ret -eq 42 ] && fail "Expect script failed."
+img_hash_unchanged
+}
+
+function img_check_fail_repair_ok()
+{
+	if [ $(id -u) == 0 ]; then
+		$CRYPTSETUP open $CS_PWPARAMS $IMG $DEV_NAME 2>/dev/null && fail
+	fi
+
+	img_run_reenc_fail
+
+	# repair metadata
+	$CRYPTSETUP repair $IMG $CS_PARAMS || fail
+
+	img_check_ok
+	img_run_reenc_ok
+}
+
 function valgrind_setup()
 {
 	bin_check valgrind
@@ -212,10 +248,10 @@ img_check_ok
 img_run_reenc_ok
 img_check_ok
 
-# Simulate old reencryption with no digest
+# Simulate old reencryption with no digest (repairable)
 img_prepare
 img_update_json 'del(.digests."2") | .config.requirements.mandatory = ["online-reencrypt"]'
-img_check_fail
+img_check_fail_repair_ok
 
 # This must fail for new releases
 echo "[2] Old reencryption in-progress (journal)"
@@ -236,7 +272,7 @@ img_update_json '
 	.digests."0".segments = ["1","2"] |
 	.digests."1".segments = ["0","3"] |
 	.config.requirements.mandatory = ["online-reencrypt"]'
-img_check_fail
+img_check_fail_repair_ok
 
 echo "[3] Old reencryption in-progress (checksum)"
 img_prepare
@@ -258,7 +294,7 @@ img_update_json '
 	.digests."0".segments = ["1","2"] |
 	.digests."1".segments = ["0","3"] |
 	.config.requirements.mandatory = ["online-reencrypt"]'
-img_check_fail
+img_check_fail_repair_ok
 
 # Note: older tools cannot create this from commandline
 echo "[4] Old decryption in-progress (journal)"
@@ -289,7 +325,7 @@ img_update_json '
 	} |
 	.digests."0".segments = ["1","2"] |
 	.config.requirements.mandatory = ["online-reencrypt"]'
-img_check_fail
+img_check_fail_repair_ok
 
 echo "[5] Old decryption in-progress (checksum)"
 img_prepare
@@ -321,7 +357,7 @@ img_update_json '
 	} |
 	.digests."0".segments = ["1","2"] |
 	.config.requirements.mandatory = ["online-reencrypt"]'
-img_check_fail
+img_check_fail_repair_ok
 
 # Note - offset is set to work with the old version (with a datashift bug)
 echo "[6] Old reencryption in-progress (datashift)"
@@ -344,7 +380,7 @@ img_update_json '
 	.digests."0".segments = ["0","2"] |
 	.digests."1".segments = ["1","3"] |
 	.config.requirements.mandatory = ["online-reencrypt"]'
-img_check_fail
+img_check_fail_repair_ok
 
 #
 # NEW metadata (with reenc digest)
@@ -360,7 +396,7 @@ img_check_ok
 # Repair must validate not only metadata, but also reencryption digest.
 img_prepare
 img_update_json 'del(.digests."2")'
-img_check_fail
+img_check_fail_repair_ok
 
 img_prepare '--reduce-device-size 2M'
 img_update_json '.keyslots."2".area.shift_size = ((.keyslots."2".area.shift_size|tonumber / 2)|tostring)'
