Enable reencryption tests using last keyslot

diff --git a/tests/reencryption-compat-test b/tests/reencryption-compat-test
--- a/tests/reencryption-compat-test
+++ b/tests/reencryption-compat-test
@@ -187,7 +187,7 @@ echo -e "$PWD2\n$PWD1" | $CRYPTSETUP -q luksAddKey -i 1 -S 3 $LOOPDEV1 || fail
 echo -e "$PWD2\n$PWD2" | $CRYPTSETUP -q luksAddKey -i 1 -S 4 $LOOPDEV1 || fail
 echo -e "$PWD2\n$PWD1" | $CRYPTSETUP -q luksAddKey -i 1 -S 5 $LOOPDEV1 || fail
 echo -e "$PWD2\n$PWD2" | $CRYPTSETUP -q luksAddKey -i 1 -S 6 $LOOPDEV1 || fail
-# echo -e "$PWD2\n$PWD3" | $CRYPTSETUP -q luksAddKey -i 1 -S 7 $LOOPDEV1 || fail (known bug, should be fixed)
+echo -e "$PWD2\n$PWD3" | $CRYPTSETUP -q luksAddKey -i 1 -S 7 $LOOPDEV1 || fail
 backup_orig
 echo $PWD2 | $REENC -i 1 -S 0 -q $LOOPDEV1 || fail
 check_slot 0 || fail "Only keyslot 0 expected to be enabled"
@@ -201,16 +201,14 @@ echo $PWD2 | $REENC -i 1 -S 6 -q $LOOPDEV1 || fail
 check_slot 6 || fail "Only keyslot 6 expected to be enabled"
 wipe $PWD2
 rollback
-#echo $PWD3 | $REENC -i 1 -S 7 -q $LOOPDEV1 || fail
-#check_slot 7 || fail "Only keyslot 7 expected to be enabled"
-#wipe $PWD3
-#rollback
+echo $PWD3 | $REENC -i 1 -S 7 -q $LOOPDEV1 || fail
+check_slot 7 || fail "Only keyslot 7 expected to be enabled"
+wipe $PWD3
+rollback
 
 echo "[6] Reencryption using all active keyslots"
-echo -e "$PWD2\n$PWD1\n$PWD2\n$PWD1\n$PWD2\n$PWD1\n$PWD2" | $REENC -i 1 -q $LOOPDEV1 || fail
-check_slot 0 1 2 3 4 5 6 || fail "Only keyslots 0 to 6 expected to be enabled"
-#echo -e "$PWD2\n$PWD1\n$PWD2\n$PWD1\n$PWD2\n$PWD1\n$PWD2\n$PWD3" | $REENC -q $LOOPDEV1 || fail
-#check_slot 0 1 2 3 4 5 6 7 || fail "All keyslots expected to be enabled"
+echo -e "$PWD2\n$PWD1\n$PWD2\n$PWD1\n$PWD2\n$PWD1\n$PWD2\n$PWD3" | $REENC -q $LOOPDEV1 || fail
+check_slot 0 1 2 3 4 5 6 7 || fail "All keyslots expected to be enabled"
 
 remove_mapping
 exit 0
