veritysetup: Support --error-as-corruption option.
The panic/restart_on_error options were introduces in kernel 6.12.

As it does not make sense to set these flags without
data corruption handling, only one option error-as-corruption
is implemented that must be used in combination with
panic/restart on corruption.

diff --git a/tests/verity-compat-test b/tests/verity-compat-test
--- a/tests/verity-compat-test
+++ b/tests/verity-compat-test
@@ -87,6 +87,19 @@ check_version() # MAJ MIN
 	return 1
 }
 
+check_version_kernel()
+{
+	KER_STR=$(uname -r)
+	[ -z "$KER_STR" ] && fail "Failed to parse kernel version."
+	KER_MAJ=$(echo $KER_STR | cut -f 1 -d.)
+	KER_MIN=$(echo $KER_STR | cut -f 2 -d.)
+
+	test $KER_MAJ -gt $1 && return 0
+	test $KER_MIN -ge $2 && return 0
+
+	return 1
+}
+
 compare_out() # $1 what, $2 expected
 {
 	OPT=$(grep -v "^#" $DEV_OUT | grep -i "$1" | sed -e s/.*\:\ // )
@@ -293,17 +306,17 @@ check_fec()
 	return $RET
 }
 
-check_option() # $1 size, $2 hash, $3 salt, $4 version, $5 hash, $6 CLI option, $7 status option
+check_option() # $1 size, $2 hash, $3 salt, $4 version, $5 hash, $6 status option, $7-$8 CLI options
 {
 	DEV_PARAMS="$LOOPDEV1 $LOOPDEV2"
 	FORMAT_PARAMS="--format=$4 --data-block-size=$1 --hash-block-size=$1 --hash=$5 --salt=$3"
 
-	echo -n "Option $6 "
+	echo -n "Option $7 / $6 "
 	$VERITYSETUP format $DEV_PARAMS $FORMAT_PARAMS >/dev/null 2>&1 || fail
-	$VERITYSETUP create $DEV_NAME $DEV_PARAMS $2 $6 >/dev/null 2>&1 || fail
+	$VERITYSETUP create $DEV_NAME $DEV_PARAMS $2 $7 $8 >/dev/null 2>&1 || fail
 	check_exists
-	$VERITYSETUP status $DEV_NAME 2>/dev/null | grep flags | grep -q $7 || fail
-	dmsetup table $DEV_NAME 2>/dev/null | grep -q $7 || fail
+	$VERITYSETUP status $DEV_NAME 2>/dev/null | grep flags | grep -q $6 || fail
+	dmsetup table $DEV_NAME 2>/dev/null | grep -q $6 || fail
 	$VERITYSETUP close $DEV_NAME >/dev/null 2>&1 || fail
 	echo "[OK]"
 }
@@ -479,20 +492,24 @@ if check_version 1 3; then
 	SALT=e48da609055204e89ae53b655ca2216dd983cf3cb829f34f63a297d106d53e2d
 	HASH=9de18652fe74edfb9b805aaed72ae2aa48f94333f1ba5c452ac33b1c39325174
 	prepare 8192 1024
-	check_option 512 $HASH $SALT 1 sha256 "--ignore-corruption" "ignore_corruption"
-	check_option 512 $HASH $SALT 1 sha256 "--restart-on-corruption" "restart_on_corruption"
-	check_option 512 $HASH $SALT 1 sha256 "--ignore-zero-blocks" "ignore_zero_blocks"
-	check_option 512 $HASH $SALT 1 sha256 "--ignore-corruption --ignore-zero-blocks" "ignore_corruption"
+	check_option 512 $HASH $SALT 1 sha256 ignore_corruption --ignore-corruption
+	check_option 512 $HASH $SALT 1 sha256 restart_on_corruption --restart-on-corruption
+	check_option 512 $HASH $SALT 1 sha256 ignore_zero_blocks --ignore-zero-blocks
+	check_option 512 $HASH $SALT 1 sha256 ignore_corruption --ignore-corruption --ignore-zero-blocks
 	if check_version 1 4; then
-		check_option 512 $HASH $SALT 1 sha256 "--check-at-most-once" "check_at_most_once"
+		check_option 512 $HASH $SALT 1 sha256 check_at_most_once --check-at-most-once
 	fi
 	if check_version 1 7; then
-		check_option 512 $HASH $SALT 1 sha256 "--panic-on-corruption" "panic_on_corruption"
+		check_option 512 $HASH $SALT 1 sha256 panic_on_corruption --panic-on-corruption
+	fi
+	if check_version_kernel 6 12; then # dm-verity 1.10+ but they forget bump version
+		check_option 512 $HASH $SALT 1 sha256 panic_on_error --error-as-corruption --panic-on-corruption
+		check_option 512 $HASH $SALT 1 sha256 restart_on_error --error-as-corruption --restart-on-corruption
 	fi
 
 	if check_version 1 9; then
 		echo "Verity data performance options test."
-		check_option 512 $HASH $SALT 1 sha256 "--use-tasklets" "try_verify_in_tasklet"
+		check_option 512 $HASH $SALT 1 sha256 try_verify_in_tasklet --use-tasklets
 	fi
 fi
 
